import os
import sys
import time
import json
import base64
import zipfile
import requests
import subprocess
from typing import Optional, Dict

# =========================================================================
# Configuration
# =========================================================================
VPS_BASE_URL = "http://127.0.0.1:9001"  # Replace with Tailscale VPS internal IP during deployment
KATFILE_API_KEY = os.environ.get("KATFILE_API_KEY", "your_katfile_api_key")
POLL_INTERVAL = 3.0  # Seconds between claims

# Path configurations for clopeux-desktop
FACEFUSION_DIR = r"C:\Users\Administrator\Desktop\Github Repos\facefusion"  # Update to local installation path
WORK_DIR = r"C:\Users\Administrator\Desktop\Github Repos\facefusion\temp_jobs"
PROMO_ASSETS_DIR = r"C:\Users\Administrator\Desktop\Github Repos\facefusion\promo_assets"

# Create directories if they do not exist
os.makedirs(WORK_DIR, exist_ok=True)
os.makedirs(PROMO_ASSETS_DIR, exist_ok=True)

# Placeholder assets to guarantee Zip file sizes match PPD limits (>6MB)
LOGO_PATH = os.path.join(PROMO_ASSETS_DIR, "logo.png")
PDF_PATH = os.path.join(PROMO_ASSETS_DIR, "community_promo.pdf")

# Generate placeholder assets if they aren't provided yet
if not os.path.exists(LOGO_PATH):
    with open(LOGO_PATH, "wb") as f:
        f.write(os.urandom(1024 * 100))  # 100KB dummy logo
if not os.path.exists(PDF_PATH):
    with open(PDF_PATH, "wb") as f:
        # Create a ~6MB padded dummy PDF containing target redirection text
        f.write(b"%PDF-1.4\n%-- PromKing & FullXXX Community Handout --\n")
        f.write(b"Telegram Channel: https://t.me/promking_tube\n")
        f.write(b"Discord Server: https://discord.gg/promking\n")
        f.write(os.urandom(1024 * 1024 * 6))  # 6MB padding bytes to cross payout thresholds


def claim_job() -> Optional[Dict]:
    """
    Poller requesting a task from the VPS Tailscale endpoint.
    """
    url = f"{VPS_BASE_URL}/api/jobs/claim"
    try:
        response = requests.post(url, timeout=10)
        if response.status_code == 200:
            return response.json()
    except Exception as e:
        print(f"[Error] Failed to connect to VPS API: {e}")
    return None


def execute_faceswap(job_id: str, payload: Dict) -> Optional[str]:
    """
    Decodes frame payloads and invokes local GPU FaceFusion engine.
    """
    source_b64 = payload.get("source_face")
    target_b64 = payload.get("target_image")

    if not source_b64 or not target_b64:
        raise ValueError("Missing frame context base64 data")

    source_path = os.path.join(WORK_DIR, f"src_{job_id}.jpg")
    target_path = os.path.join(WORK_DIR, f"target_{job_id}.jpg")
    output_path = os.path.join(WORK_DIR, f"output_{job_id}.jpg")

    # Write binary images to work folder
    with open(source_path, "wb") as f:
        f.write(base64.b64decode(source_b64))
    with open(target_path, "wb") as f:
        f.write(base64.b64decode(target_b64))

    # Invoke FaceFusion Headless execution
    # Using recommended frame processors and CUDA GPU acceleration
    cmd = [
        sys.executable, "facefusion.py", "headless-run",
        "--source-paths", source_path,
        "--target-path", target_path,
        "--output-path", output_path,
        "--processors", "face_swapper",
        "--execution-providers", "cuda"
    ]

    print(f"[Worker] Initiating FaceFusion GPU process for Job: {job_id}...")
    result = subprocess.run(cmd, cwd=FACEFUSION_DIR, capture_output=True, text=True)

    if result.returncode != 0:
        print(f"[Error] FaceFusion process failed: {result.stderr}")
        raise RuntimeError(f"FaceFusion process failed: {result.stderr}")

    if not os.path.exists(output_path):
        raise FileNotFoundError("Output image was not generated by FaceFusion")

    # Clean up temporary sources immediately for space conservation
    if os.path.exists(source_path):
        os.remove(source_path)
    if os.path.exists(target_path):
        os.remove(target_path)

    return output_path


def package_ppd_archive(job_id: str, output_image: str) -> str:
    """
    Compresses faceswap result along with promotional handouts
    and logos to guarantee a PPD payout size (>6MB).
    """
    zip_path = os.path.join(WORK_DIR, f"faceswap_{job_id}.zip")
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        zipf.write(output_image, arcname="faceswap_result.jpg")
        zipf.write(LOGO_PATH, arcname="promking_logo.png")
        zipf.write(PDF_PATH, arcname="join_our_community.pdf")

    # Clean up bare output image after compression
    if os.path.exists(output_image):
        os.remove(output_image)

    return zip_path


def upload_to_katfile(file_path: str) -> str:
    """
    Standard KatFile XFileSharing API upload implementation.
    """
    print(f"[Worker] Fetching upload server URL from KatFile...")
    server_url = "https://katfile.space/api/upload/server"
    resp = requests.get(server_url, params={"key": KATFILE_API_KEY}, timeout=15)
    data = resp.json()

    if data.get("status") != 200:
        raise RuntimeError(f"Failed to fetch KatFile upload server: {data.get('msg')}")

    upload_url = data["result"]
    sess_id = data["sess_id"]

    print(f"[Worker] Uploading PPD zip container to KatFile server: {upload_url}")
    with open(file_path, 'rb') as f:
        files = {'file_0': f}
        post_data = {
            'sess_id': sess_id,
            'utype': 'prem'  # Defaults to affiliate premium configuration
        }
        upload_resp = requests.post(upload_url, data=post_data, files=files, timeout=120)
        upload_data = upload_resp.json()

    if isinstance(upload_data, list) and len(upload_data) > 0:
        result_item = upload_data[0]
        download_url = result_item.get("download_url")
        if download_url:
            return download_url

    raise RuntimeError(f"KatFile upload response parsed unsuccessfully: {upload_data}")


def complete_job(job_id: str, status: str, result_url: Optional[str] = None, error: Optional[str] = None):
    """
    Commits status states and generated PPD URL back to VPS queue.
    """
    url = f"{VPS_BASE_URL}/api/jobs/{job_id}/complete"
    payload = {
        "status": status,
        "result": {"download_url": result_url} if result_url else None,
        "error": error
    }
    try:
        requests.post(url, json=payload, timeout=10)
        print(f"[Worker] Job {job_id} successfully marked as {status}.")
    except Exception as e:
        print(f"[Error] Failed to submit job completion back to VPS: {e}")


def main():
    print("[Worker] Local GPU FaceFusion Pipeline Worker started successfully.")
    print("[Worker] Restricted Tailscale connection established. Long-polling for jobs...")
    while True:
        job = claim_job()
        if job:
            job_id = job.get("id")
            payload = job.get("payload") or {}
            print(f"\n[Worker] Claimed job {job_id} successfully! Initiating processing...")
            try:
                # 1. Execute swapper on local GPU
                output_path = execute_faceswap(job_id, payload)
                if not output_path:
                    raise RuntimeError("Faceswap execution failed to yield output path")

                # 2. Bundle PPD payout container with logo + PDF links
                zip_archive = package_ppd_archive(job_id, output_path)

                # 3. Upload container to KatFile affiliate space
                download_link = upload_to_katfile(zip_archive)

                # 4. Commit success download url to VPS queue
                complete_job(job_id, "succeeded", result_url=download_link)

                # Clean up local archive immediately
                if os.path.exists(zip_archive):
                    os.remove(zip_archive)

            except Exception as ex:
                print(f"[Error] Execution fail on Job {job_id}: {ex}")
                complete_job(job_id, "failed", error=str(ex))
        else:
            time.sleep(POLL_INTERVAL)


if __name__ == "__main__":
    main()
